import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Outfit } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const outfit = Outfit({ subsets: ['latin'], weight:["400","500","600","700"] });

export const metadata = {
    title: "CC tutor notes",
    description: "Generated by create next app",
};

export default function RootLayout({ children } : { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={outfit.className}>{children}</body>
        </html>
    );
}