import type {Metadata} from "next";
import "@/app/globals.css";
import {inter} from "@/lib/ui/fonts";
import Link from "next/link";
import Footer from "@/lib/ui/Footer";
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs';

export const metadata: Metadata = {
    title: "Concord College tutor notes",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en">
            <head>
                <title>Concord College tutor notes</title>
                <link rel="icon" type="image/x-icon"
                      href="https://concordcollegeuk.com/wp-content/uploads/2023/11/logo.svg"/>
            </head>

            <body className={inter.className}>


            <nav
                className="bg-white border-gray-200 dark:bg-gray-900">
                <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
                    <a href="https://concordcollege" className="flex items-center space-x-3 rtl:space-x-reverse">
                        <img src="https://concordcollegeuk.com/wp-content/uploads/2023/11/logo.svg" className="h-8"
                             alt="Flowbite Logo"/>
                        <span
                            className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Concord Student Hub</span>
                    </a>

                    <div className="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
                         id="navbar-sticky">
                        <ul className="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                            <li>
                                <Link href="/"
                                      className="block py-2 px-3 text-white bg-blue-700 rounded-sm md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500"
                                      aria-current="page">Home</Link>
                            </li>
                            <li>
                                <Link href="/revision"
                                      className="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Revision
                                    Notes</Link>
                            </li>
                            <li>
                                <Link href="/olympiads"
                                      className="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Olympiads</Link>
                            </li>
                            <li>
                                <Link href="/ec"
                                      className="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Extracurriculars</Link>
                            </li>
                            <li>
                                <Link href="/upload"
                                      className="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Upload</Link>
                            </li>
                            <li>
                                <SignedOut>
                                    <SignInButton/>
                                </SignedOut>
                                <SignedIn>
                                    <UserButton/>
                                </SignedIn>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div className='min-h-screen'>
                {children}
            </div>
            <Footer/>
            </body>
            </html>
        </ClerkProvider>
    );
}